name: 🔍 CI

on:
  push:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  SKIP_ENV_VALIDATION: true

jobs:
  ci:
    name: 🔍 CI
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: 🟢 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install

      # - name: 🔧 Install Playwright Browsers
      #   run: pnpm playwright install --with-deps

      # - name: ✍️ Markdownlint
      #   run: pnpm lint:md

      # - name: 🎨 Check formatting
      #   run: pnpm format:check

      - name: ✅ Lint
        run: pnpm lint

      - name: ⚡ Check types
        run: pnpm typecheck

      - name: 🧪 Tests
        run: pnpm test

      # - name: 🧪 E2E Tests
      #   run: pnpm test:e2e

      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
